spring.application.name=yumyum-backend

logging.level.com.ssafy=trace
logging.pattern.console=%d{HH:mm:ss} [%level] %c{36} %m%n

# 뷰 리졸버 설정 (필요 시 JSP 페이지 매핑용)
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp



# 데이터베이스(MySQL) 연결 커넥션 설정
spring.datasource.url=jdbc:mysql://localhost:3307/yamyamdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=ssafy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

# MongoDB (채팅)
spring.data.mongodb.uri=mongodb://localhost:27017/yamyamdb





# 동영상 업로드 저장 경로 (새로 올린 영상 저장)
#yamyam.video.upload-dir=${user.home}/uploads/videos
yamyam.video.upload-dir=src/main/resources/static/videos
# 로컬 임시 파일 저장 위치 설정 (동영상 업로드 공간)
spring.servlet.multipart.location=${user.home}/uploads
# 임시 메모리 저장 파일 크기 한계선
spring.servlet.multipart.file-size-threshold=10MB
# 식단 동영상 처리를 위한 파일당 최대 용량 상한선 (50MB)
spring.servlet.multipart.max-file-size=50MB
# 한 번에 요청 가능한 전체 멀티파트 데이터 용량 상한선
spring.servlet.multipart.max-request-size=50MB

# ==========================================
# MyBatis ?? ??
# ==========================================
# MyBatis? XML ???? ??? ??? ?????.
mybatis.mapper-locations=classpath:mapper/**/*.xml

# (?? ??) DB ??? snake_case(team_id)? Java? camelCase(teamId)? ?? ??? ???.
mybatis.configuration.map-underscore-to-camel-case=true

# MyBatis? Java Enum? DB? ??? ? ??? ?? ???(String) ?? ??? ????? ??
mybatis.configuration.default-enum-type-handler=org.apache.ibatis.type.EnumTypeHandler


# JWT ??
#??: ???(secret)? ?? 32???(256??) ??? ?? ??? ?????? ??? ? ?!
jwt.secret=vAmYvAmYvAmYvAmYvAmYvAmYvAmYvAmYvAmYvAmYvAmYvAmYvAmYvAmY
# ?? ??: 86400000 ??? = 24?? (??)
jwt.expiration=86400000


# Spring AI - OpenAI (? ??? ?? ?????)
spring.ai.openai.api-key=S15P02AM06-d567cf77-e1a1-46c0-92b2-dbad03b22e6a
spring.ai.openai.base-url=https://gms.ssafy.io/gmsapi/api.openai.com
spring.ai.openai.chat.options.model=gpt-4o

# ?? ? ??? ???? ?? ?? ????? ??? ????
spring.autoconfigure.exclude=org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration